### ISSUE TITLE
Need a better README

### ISSUE THREAD

**Issue by MaxBubblegum47** [Zacomo/Tweet-Tracker#1]
I'd like to test program's functionality, but I cannot make it run correctly neither on Eclipse or Intellij. I also try to make it run on terminal with no results :(

**Comment by Zacomo** [comment]
Ciao Lorenzo,

che problemi hai riscontrato? Ho parlato con un altro ragazzo e ha letto male la versione di JavaFX da installare (aveva messo la 11 ma in realtà serve dalla 15 in su), hai un problema simile?
Ho bisogno di qualche dettaglio in più per provare ad aiutarti.

Attendo tue,
Giacomo.

Da: Lorenzo ***@***.***>
Inviato: venerdì 30 aprile 2021 14:03
A: ***@***.***>
Cc: ***@***.***>
Oggetto: [Zacomo/Tweet-Tracker] Need a better README (#1)


I'd like to test program's functionality, but I cannot make it run correctly neither on Eclipse or Intellij. I also try to make it run on terminal with no results :(

**Comment by Zacomo** [comment]
> I'd like to test program's functionality, but I cannot make it run correctly neither on Eclipse or Intellij. I also try to make it run on terminal with no results :(

Ciao Lorenzo, che problemi hai riscontrato? Hai controllato di aver scaricato la giusta versione di Java FX (va bene dalla 15 in su)?
Ho bisogno di qualche dettaglio in più per provare ad aiutarti.

**Comment by MaxBubblegum47** [comment]
Grazie mille per il consiglio! Sisi alla fine siamo riusciti a risolvere il problema. è che avevamo qualche problema a far partire il progetto e ci interessava vederlo in azione perché dobbiamo realizzare una applicazione che ha alcune peculiarità in comune con il tuo progetto! Scusami per l'apertura dell'issue così clickbait, era per attirare la tua attenzione perché avevamo una certa urgenza

**Comment by Zacomo** [comment]
Sì, ho già sentito un altro ragazzo quindi so che dovete fare un progetto di questo tipo. Se avete dei problemi che proprio non riuscite a risolvere (relativi al funzionamento del codice in questo repository) posso provare ad aiutarvi, basta scrivermi via mail. Tenete comunque a mente che non guardo il codice da ottobre 2020, probabilmente la tesi è più precisa delle risposte che potrei darvi io.
In qualsiasi caso sono disponibile per provare a darvi dei chiarimenti, in bocca al lupo con il progetto!
